on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
name: test
jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
          
  test:
    needs: lint
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: false
        
    - name: build
      run: make get build
      
    - name: wol
      run: make wol
      
    - name: uninstall
      run: make uninstall
      
    - name: install
      run: make install
      
    - name: test
      run: make test
      
    - name: logs
      run: make logs
      if: always()
      
    - name: Suspend
      run: make suspend
      if: always()
    timeout-minutes: 30