on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
name: test
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: build
      run: make get build
    - name: wol
      run: make wol
    # - name: uninstall
    #   run: make uninstall
    - name: install
      run: make install
    - name: test
      run: make test
    - name: logs
      run: make logs
      if: always()
    - name: Suspend node0
      run: make suspend
      if: always()
    timeout-minutes: 30