on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
name: test
jobs:
  uninstall:
    runs-on: master
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: uninstall
      run: make uninstall
    - name: install
      run: make install